spring:
  profiles:
    active: dev
---
server:
  port: 8005
  max-http-header-size: 4048576 #解决request header is too large异常
spring:
  application:
    name: COMMON-SERVICE #服务名（不要使用下划线）
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #服务注册中心的地址，去这里注册服务
---
server:
  port: 8006
  max-http-header-size: 4048576 #解决Request header is too large异常
spring:
  application:
    name: COMMON-SERVICE-TEST #服务名（不要使用下划线）
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #服务注册中心的地址，去这里注册服务
